"""poster_shares_and_notifications

Revision ID: 5ba06aedc5cc
Revises: 0005_widen_candidate_symbol_column
Create Date: 2026-08-20 11:28:46.543102+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba06aedc5cc'
down_revision: Union[str, None] = '0005_widen_candidate_symbol_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_poster_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_poster_id'], ['saved_designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_notifications_created_at'), 'app_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_notifications_id'), 'app_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_app_notifications_user_id'), 'app_notifications', ['user_id'], unique=False)
    op.create_table('poster_shares',
    sa.Column('poster_id', sa.String(length=36), nullable=False),
    sa.Column('shared_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('shared_with_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['saved_designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poster_shares_created_at'), 'poster_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_poster_shares_id'), 'poster_shares', ['id'], unique=False)
    op.create_index(op.f('ix_poster_shares_poster_id'), 'poster_shares', ['poster_id'], unique=False)
    op.create_index(op.f('ix_poster_shares_shared_by_user_id'), 'poster_shares', ['shared_by_user_id'], unique=False)
    op.create_index(op.f('ix_poster_shares_shared_with_user_id'), 'poster_shares', ['shared_with_user_id'], unique=False)
    op.alter_column('field_activity_logs', 'submitted_by_role',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_field_activity_logs_submitted_by'), 'field_activity_logs', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_field_activity_logs_submitted_by_role'), 'field_activity_logs', ['submitted_by_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_activity_logs_submitted_by_role'), table_name='field_activity_logs')
    op.drop_index(op.f('ix_field_activity_logs_submitted_by'), table_name='field_activity_logs')
    op.alter_column('field_activity_logs', 'submitted_by_role',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index(op.f('ix_poster_shares_shared_with_user_id'), table_name='poster_shares')
    op.drop_index(op.f('ix_poster_shares_shared_by_user_id'), table_name='poster_shares')
    op.drop_index(op.f('ix_poster_shares_poster_id'), table_name='poster_shares')
    op.drop_index(op.f('ix_poster_shares_id'), table_name='poster_shares')
    op.drop_index(op.f('ix_poster_shares_created_at'), table_name='poster_shares')
    op.drop_table('poster_shares')
    op.drop_index(op.f('ix_app_notifications_user_id'), table_name='app_notifications')
    op.drop_index(op.f('ix_app_notifications_id'), table_name='app_notifications')
    op.drop_index(op.f('ix_app_notifications_created_at'), table_name='app_notifications')
    op.drop_table('app_notifications')
    # ### end Alembic commands ###
